apiVersion: skaffold/v2beta23
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/namespace/*
      - ./infra/k8s/blockchain/secrets/*
      - ./infra/k8s/blockchain/configmap/*
      - ./infra/k8s/blockchain/services/*
      - ./infra/k8s/blockchain/deployments/*
      - ./infra/k8s-dev/*
      - ./infra/k8s/explorer/block-explorer-lite/*
      - ./infra/k8s/explorer/cakeshop/*