apiVersion: skaffold/v2beta23
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/namespace/*
      - ./infra/k8s/blockchain/secrets/*
      - ./infra/k8s/blockchain/configmap/*
      - ./infra/k8s/blockchain/services/*
      - ./infra/k8s/blockchain/deployments/*
      # - ./infra/k8s/explorer/cakeshop/*
      # - ./infra/k8s/database/postgres/*
      - ./infra/k8s/smart-contracts/permissioning-dapp/*
      # - ./infra/k8s/explorer/blockscout/*
      - ./infra/k8s/explorer/block-explorer-lite/*
      # - ./infra/k8s/monitoring/*
      - ./infra/k8s-prod/*