apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  labels:
    app: blockscout
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      initContainers:
        - name: init-validator
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgresql-db-0.postgresql-db-service.testnet.svc.cluster.local; do echo waiting for PostgreSQL to bootup; sleep 5; done"] 
      containers:
        - name: blockscout
          image: rg.fr-par.scw.cloud/trustyline/blockscout:latest
          imagePullPolicy: IfNotPresent
          env:
              - name: VALIDATOR1_PUBKEY
                valueFrom:
                  configMapKeyRef:
                    name: testnet-validators-pubkey
                    key: validator1PubKey
              - name: VALIDATOR2_PUBKEY
                valueFrom:
                  configMapKeyRef:
                    name: testnet-validators-pubkey
                    key: validator2PubKey
          volumeMounts:
            - name: genesis-config
              mountPath: /etc/genesis
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec /opt/app/besu/bin/besu \
                --data-path=data \
                --rpc-http-enabled \
                --rpc-http-api=ETH,NET,WEB3,MINER,IBFT,ADMIN,TRACE,TXPOOL \
                --rpc-ws-enabled \
                --rpc-ws-api=ETH,NET,WEB3,MINER,IBFT,ADMIN,TRACE,TXPOOL \
                --host-allowlist="*" \
                --rpc-http-cors-origins="all" \
                --genesis-file=/etc/genesis/genesis.json \
                --Xdns-enabled=true --Xdns-update-enabled=true \
                --bootnodes=enode://${VALIDATOR1_PUBKEY}@validator1-0.testnet-validator1.testnet.svc.cluster.local:30303,enode://${VALIDATOR2_PUBKEY}@validator2-0.testnet-validator2.testnet.svc.cluster.local:30303
          envFrom:
            - configMapRef:
                name: blockscout-config
      # Volume Claim
      volumes:
        - name: data
          emptyDir:
            sizeLimit: "1Gi"
        - name: genesis-config
          configMap:
            name: testnet-genesis-configmap
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blockscout
  namespace: testnet
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: blockscout