apiVersion: v1
kind: ConfigMap
metadata:
  name: blockscout-config
  labels:
    app: blockscout-config
  namespace: testnet
data:
  PORT: "4000"
  MIX_ENV: "prod"
  SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5" 
  ETHEREUM_JSONRPC_VARIANT: "besu"
  ETHEREUM_JSONRPC_HTTP_URL: "localhost:8545"
  ETHEREUM_JSONRPC_WS_URL: "ws://localhost:8546"
  ETHEREUM_JSONRPC_TRACE_URL: "localhost:8545"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "admin"
  SUBNETWORK: ""
  COIN: "ETH"
  DATABASE_URL: "postgresql://admin:password@postgresql-db-0.postgresql-db-service.testnet.svc.cluster.local:5432/blockscout?ssl=false"
  POSTGRES_HOST_AUTH_METHOD: "trust"