apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  labels:
    app: blockscout
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      initContainers:
        - name: init-blockscout
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgresql-db-0.postgresql-db-service.testnet.svc.cluster.local; do echo waiting for PostgresDB to bootup; sleep 5; done"]
      containers:
        - name: blockscout
          image: achoisy/blockscout:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: webserver
              protocol: TCP
          envFrom:
            - configMapRef:
                name: blockscout-config
---
apiVersion: v1
kind: Service
metadata:
  name: blockscout
  namespace: testnet
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: blockscout