apiVersion: v1
kind: ConfigMap
metadata:
  name: blockscout-config
  labels:
    app: blockscout-config
  namespace: testnet
data:
  NETWORK: "DEV"
  SUBNETWORK: "DEV Testnet"
  LOGO: "/images/blockscout_logo.svg"
  COIN: "TRY"
  LOGO_FOOTER: "/images/blockscout_logo.svg"
  ETHEREUM_JSONRPC_VARIANT: "besu"
  ETHEREUM_JSONRPC_HTTP_URL: "validator1-0.testnet-validator1.testnet.svc.cluster.local:8545"
  ETHEREUM_JSONRPC_TRACE_URL: "validator1-0.testnet-validator1.testnet.svc.cluster.local:8545"
  ETHEREUM_JSONRPC_WS_URL: "ws://validator1-0.testnet-validator1.testnet.svc.cluster.local:8546"
  DATABASE_URL: "postgresql://admin:password@postgresql-db-0.postgresql-db-service.testnet.svc.cluster.local:5432/blockscout"