apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8545: "testnet/testnet-rpcnode:8545"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rpcnode
  namespace: testnet
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: testnet-rpcnode
spec:
  rules:
  - host: rpc.testnet.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testnet-rpcnode
            port:
              number: 8545
  - host: ws.testnet.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testnet-rpcnode
            port:
              number: 8546
  - host: graphql.testnet.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testnet-rpcnode
            port:
              number: 8547