apiVersion: networking.k8s.io/v1
kind : Ingress
metadata:
  name: ingress-permissioning
  namespace: testnet
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: permissioning.testnet.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: permissioning-smart-contract
            port:
              number: 80